'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
'     o código for regenerado.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NEGOCIOPRECISO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property avatardefault_92824() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("avatardefault_92824", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_bookmark_icon_34486() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book-bookmark-icon_34486", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_bookmark_icon_344861() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book-bookmark-icon_344861", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_configuration_22776() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_configuration_22776", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fullconfiguration_settings_4501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullconfiguration_settings_4501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help_icon_icons_com_73700() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_icon-icons.com_73700", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_chamada_em_conferência_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-chamada-em-conferência-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_chamada_em_conferência_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-chamada-em-conferência-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_chamada_em_conferência_641() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-chamada-em-conferência-641", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_nome_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-nome-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lock_padlock_symbol_for_protect_icon_icons_com_56926() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock-padlock-symbol-for-protect_icon-icons.com_56926", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pie_chart_paper_notes_document_icon_131801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie_chart_paper_notes_document_icon_131801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutdown_off_close_exit_15253() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown_off_close_exit_15253", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property statistic_chart_graph_report_finance_icon_191150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("statistic_chart_graph_report_finance_icon_191150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stocks_graphic_with_a_magnifier_tool_icon_icons_com_70602() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stocks-graphic-with-a-magnifier-tool_icon-icons.com_70602", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property system_applications_thesource_thebook_13028() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system_applications_thesource_thebook_13028", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user_icon_icons_com_57997() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_icon-icons.com_57997", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users_clients_group_16774() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users_clients_group_16774", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users_clients_group_16774__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users_clients_group_16774 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property users_clients_group_167741() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("users_clients_group_167741", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
